services:
    napcat:
        environment:
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        ports:
            - 11000:3000
            - 11001:3001
            - 11002:6099
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: napcat-njk
        network_mode: bridge
        image: mlikiowa/napcat-docker:latest
        mem_limit: 512m
        memswap_limit: 1.5g